### PR TITLE
[#49] Catch CabalException in main functions

### LINKED ISSUE #49: Catch CabalException in main functions

### PR DESCRIPTION
**Pull request by vrom911**
Resolves #49

### CODE REVIEW

File: src/Extensions.hs [hunk 1]
```diff
@@ -39,8 +40,8 @@ type ExtensionsResult = Either ExtensionsError (Set OnOffExtension)
 data ExtensionsError
     -- | Parse error during module extensions parsing.
     = ModuleParseError FilePath ParseError
-    -- | Parse error during cabal extensions parsing.
-    | CabalParseError
+    -- |Error during @.cabal@ file reading/parsing.
```
Comment (chshersh) [inline src/Extensions.hs]:
```suggestion
    -- | Error during @.cabal@ file reading/parsing.
```

File: src/Extensions.hs [hunk 2]
```diff
@@ -63,30 +64,27 @@ getPackageExtentions cabalFile = do
...
-    cabalMap <- parseCabalFileExtensions cabalFile
-    pure $ merge
-        (mapMissing cabalNotSource) -- in cabal but not in sources
-        (mapMissing sourceNotCabal) -- in sources but not in cabal
-        (zipWithMatched cabalAndSource) -- in cabal and sources
-        cabalMap
-        sourcesMap
+    cabalRes <- parseCabalHandleException cabalFile
+    pure $ case cabalRes of
+        Left err -> Map.map (const err) sourcesMap
```
Comment (chshersh) [inline src/Extensions.hs]: Actually, you can write `err <$ sourcesMap` since `Map` implements a `Functor` instance. And remember reading something about efficient implementation of a function, that sets all values to some specific value via `<$`. From the implementation I can see that the implementation is manual for this function:

* https://hackage.haskell.org/package/containers-0.6.2.1/docs/src/Data.Map.Internal.html#line-4196

File: src/Extensions.hs [hunk 3]
```diff
@@ -104,41 +102,37 @@ getPackageExtentionsBySources cabalFile sourcesMap = do
...
 getModuleExtentions cabalFile path = do
-    cabalMap <- parseCabalFileExtensions cabalFile
-    case Map.lookup path cabalMap of
-        Nothing -> pure $ Left $ NotCabalModule path
-        Just cabalExts -> do
-            moduleRes <- parseFile path
-            pure $ mergeCabalAndModule cabalExts path moduleRes
+    cabalRes <- parseCabalHandleException cabalFile
+    case cabalRes of
+        Left err -> pure err
```
Comment (chshersh) [inline src/Extensions.hs]: Would it make sense to use `LambaCase` here? :thinking:

**Review by chshersh — APPROVED** [review]
Looks great!
