### PR TITLE
[#13] Parser doesn't fail when meets unknown extension

### LINKED ISSUE #13: Parser doesn't fail when meets unknown extension

### PR DESCRIPTION
**Pull request by chshersh**
Resolves #13

### CODE REVIEW

File: test/Test/Extensions/Parser.hs [hunk 1]
```diff
@@ -2,17 +2,27 @@ module Test.Extensions.Parser
...
 import Extensions.OnOff (OnOffExtension (..))
-import Extensions.Parser (parseSource)
+import Extensions.Parser (ParseError (..), parseSource)
 
 
 parserSpec :: Spec
 parserSpec = describe "Haskell file Extensions Parser" $ do
+    itShouldFail
+        "{-# LANGUAGE DependentTypes #-}"
+        (UnknownExtensions $ "DependentTypes" :| [])
```
Comment (vrom911) [inline test/Test/Extensions/Parser.hs:19]: :rofl:

**Review by vrom911 — APPROVED** [review]
Cool :1st_place_medal:
